# Generated by Django 3.1.4 on 2020-12-20 03:04
from django.db import migrations
from django.db import models

import blog.models


class Migration(migrations.Migration):

    dependencies = [("blog", "0002_auto_20201211_0846")]

    operations = [
        migrations.AddField(
            model_name="article",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to=blog.models.get_file_path
            ),
        )
    ]
